steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true
  - imports:
      align: global
      list_align: after_alias
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
  - trailing_whitespace: {}
columns: 100
newline: native
language_extensions:
  - OverloadedStrings
  - TypeFamilies
  - MultiParamTypeClasses
  - TupleSections
  - LambdaCase
  - GADTs
  - NoImplicitPrelude
  - ExistentialQuantification
  - TemplateHaskell
  - QuasiQuotes
  - FlexibleInstances
  - FlexibleContexts
  - FunctionalDependencies
  - NamedFieldPuns
  - TypeSynonymInstances
