name: marvin
version: '0.3'
synopsis: A framework for modular, portable chat bots.
description: ! 'A framework for writing portable chat bots. Inspired by hubot.


  The best way to get started with this library is with the documentation on readthedocs:
  <https://marvin.readthedocs.io>.


  When upgrading to a new version also be aware of the potential breaking changes,
  listed here: <https://marvin.readthedocs.io/en/latest/breaking-changes.html>.'
category: Development
author: Justus Adam
maintainer: dev@justus.science
copyright: © 2016, 2017 Justus Adam
license: BSD3
github: JustusAdam/marvin
homepage: https://marvin.readthedocs.io
extra-source-files:
- README.md
- CHANGELOG.md
- preprocessor/Main.mustache
default-extensions:
- OverloadedStrings
- TypeFamilies
- MultiParamTypeClasses
- TupleSections
- GADTs
dependencies:
- base >=4.7 && <5
- aeson >=0.11 && <2
when:
  - condition: impl(ghc >= 8.2.0)
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
library:
  source-dirs: src
  default-extensions:
  - LambdaCase
  - TemplateHaskell
  - QuasiQuotes
  - FlexibleInstances
  - FlexibleContexts
  - FunctionalDependencies
  - NamedFieldPuns
  - TypeSynonymInstances
  - TypeOperators
  - DataKinds
  exposed-modules:
  - Marvin
  - Marvin.Prelude
  - Marvin.Types
  - Marvin.Run
  - Marvin.Handler
  - Marvin.Util.Regex
  - Marvin.Util.Random
  - Marvin.Util.JSON
  - Marvin.Util.Config
  - Marvin.Adapter
  - Marvin.Adapter.Shell
  - Marvin.Adapter.IRC
  - Marvin.Adapter.Slack.RTM
  - Marvin.Adapter.Slack.EventsAPI
  - Marvin.Adapter.Slack.Internal
  - Marvin.Adapter.Telegram.Push
  - Marvin.Adapter.Telegram.Poll
  - Marvin.Adapter.Telegram.Internal
  other-modules:
  - Marvin.Adapter.Slack.Internal.Common
  - Marvin.Adapter.Slack.Internal.Types
  - Marvin.Adapter.Telegram.Internal.Common
  - Marvin.Internal
  - Marvin.Internal.LensClasses
  - Marvin.Internal.Types
  - Marvin.Internal.Values
  - Util
  - Paths_marvin
  dependencies:
  - wreq >=0.4 && <0.6
  - mtl >=2.2 && <3
  - microlens-platform >= 0.2
  - text-icu >=0.6 && <0.8
  - vector >=0.11 && <1
  - configurator >=0.3
  - bytestring >=0.10
  - monad-logger >=0.3
  - websockets >=0.9
  - network-uri >=2.6
  - wuss >=1.0
  - random >=1.0
  - hashable >=1.0
  - text >=1.0
  - unordered-containers >=0.2
  - marvin-interpolate >=1.0
  - lifted-base >=0.2
  - lifted-async >=0.8
  - wai >=3 && <4
  - warp >=3 && <4
  - warp-tls >=3 && <4
  - haskeline >=0.7 && <1
  - monad-loops >=0.4
  - time >=1 && <2
  - transformers-base >=0.4 && <0.5
  - monad-control >=1 && <2
  - deepseq >=1 && <2
  - http-types >=0.8 && <1.0
  - http-client >=0.4 && <0.7
  - http-client-tls >=0.2 && <0.4
  - optparse-applicative >=0.11 && <1
  - transformers >=0.4
  - conduit >=1.2
  - irc-conduit >=0.2
  - filepath >=1.4
  - directory >=1.2
  - labels >= 0.3
executables:
  marvin-pp:
    main: Main.hs
    source-dirs: preprocessor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mustache >=2.0
    - directory >=1.2
    - filepath >=1.4
    - marvin
    - configurator >=0.3
    - optparse-applicative >=0.11 && <1
    - bytestring >=0.10
    - text >=1.0
    - vector >=0.11 && <1
  marvin-init:
    main: Main.hs
    source-dirs: initializer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mustache >=2.0
    - directory >=1.2
    - filepath >=1.4
    - optparse-applicative >=0.11 && <1
    - text >=1.0
    - ansi-wl-pprint == 0.6.*
tests:
  marvin-unit-tests:
    main: Spec.hs
    other-modules: ExternalScripts
    source-dirs:
    - test
    - preprocessor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marvin
    - hspec >=2.2
data-files:
- resources/initializer/*
stability: experimental
